# SYNTAX

#### np.array()- to convert list into arrays
#### variable.shape -  will tell you the shape of the array like how may rows and columns
#### variable.ndim - will tells the dimensions of an array
#### variable.size - total no of elements present
#### np.zeros() - to create zero arrays
#### np.ones() - to create one's arrays
#### np.arange() -  create a range of values
#### np.linspace() - create a range of values with equal intervals
#### np.arange(1,100,2, dtype=np.float64 ), np.array([ ],dtype=np.int64) - converting into another datatype
#### variable[variable>=] -  boolean indexing and filtering
#### reshape() - reshaping the array
#### variable.transpose() / variable.T - transpose the array
#### variable.flatten() - Flatten the array
#### np.concatenate([var1], [var2]) - to concatenate two different arrays
#### var1,var2 = np.split(var,2)
####  var = np.random.normal(size=(rowsxcols)) -creating random no
#### var = np.random.randint(low,high,size=(rowxcols)) - creating random integer
#### np.random.shuffle(var) - shuffling the created nos
#### np.random.permutation(range/var) -  ordering/permuting the numbers

!pip install numpy

In [6]:
import numpy as np

## Creating numpy array using np.array function

In [7]:
## Creating a list to convert
price = [ 12,178,34,60,90,96,45]
type(price)

list

In [11]:
#converting using np.array function
price_array = np.array(price)
price_array

array([ 12, 178,  34,  60,  90,  96,  45])

In [10]:
type(price_array)

numpy.ndarray

In [13]:
#checking the elements inside array what type of datatype it is
price_array.dtype

dtype('int32')

In [15]:
#checking the shape
price_array.shape

(7,)

In [16]:
price_array.ndim

1

## creating 2-d array

In [19]:
array_2d = np.array([
         [2,4,5],
         [4,6,8],
         [6,8,1]
            ])

In [21]:
print(array_2d)

[[2 4 5]
 [4 6 8]
 [6 8 1]]


In [22]:
#checking the shape
array_2d.shape

(3, 3)

In [24]:
#checking the dimension
array_2d.ndim

2

In [25]:
# total number of elements present
array_2d.size

9

## creating 3-d array

In [26]:
array_3d = np.array(
                    [
                        [[1,2],[3,4],
                         [6,3],[7,2]]
                    ]
)

In [31]:
array_3d

array([[[1, 2],
        [3, 4],
        [6, 3],
        [7, 2]]])

In [27]:
array_3d.shape

(1, 4, 2)

In [28]:
array_3d.ndim

3

In [30]:
array_3d.size

8

In [44]:
array_3d = np.array(
                    [
                           [[3,4,5],
                            [5,6,7]],
                           [[65,7,5],
                           [59,64,78]],
                          [[45,76,46],
                          [65,89,23]]
                        
                    ]
)

In [45]:
array_3d.shape

(3, 2, 3)

In [46]:
array_3d.ndim

3

In [47]:
array_3d.size

18

## creating zeros arrays and ones arrays

In [32]:
zero_1d = np.zeros(5)

In [33]:
zero_1d

array([0., 0., 0., 0., 0.])

In [36]:
zero_2d = np.zeros((5,5))

In [37]:
zero_2d

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [48]:
zero_3d = np.zeros((4,2,5))

In [49]:
zero_3d

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [54]:
one_1d = np.ones(5)

In [55]:
one_1d

array([1., 1., 1., 1., 1.])

In [57]:
one_2d=np.ones((3,6))

In [58]:
one_2d

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

## np.arange()

In [64]:
range = np.arange(1,50,3)

In [65]:
range

array([ 1,  4,  7, 10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49])

In [66]:
ar= np.array(range)

In [67]:
print(ar)

[ 1  4  7 10 13 16 19 22 25 28 31 34 37 40 43 46 49]


## np.linspace()

In [73]:
lin= np.linspace(2,10,100)

In [74]:
print(lin)

[ 2.          2.08080808  2.16161616  2.24242424  2.32323232  2.4040404
  2.48484848  2.56565657  2.64646465  2.72727273  2.80808081  2.88888889
  2.96969697  3.05050505  3.13131313  3.21212121  3.29292929  3.37373737
  3.45454545  3.53535354  3.61616162  3.6969697   3.77777778  3.85858586
  3.93939394  4.02020202  4.1010101   4.18181818  4.26262626  4.34343434
  4.42424242  4.50505051  4.58585859  4.66666667  4.74747475  4.82828283
  4.90909091  4.98989899  5.07070707  5.15151515  5.23232323  5.31313131
  5.39393939  5.47474747  5.55555556  5.63636364  5.71717172  5.7979798
  5.87878788  5.95959596  6.04040404  6.12121212  6.2020202   6.28282828
  6.36363636  6.44444444  6.52525253  6.60606061  6.68686869  6.76767677
  6.84848485  6.92929293  7.01010101  7.09090909  7.17171717  7.25252525
  7.33333333  7.41414141  7.49494949  7.57575758  7.65656566  7.73737374
  7.81818182  7.8989899   7.97979798  8.06060606  8.14141414  8.22222222
  8.3030303   8.38383838  8.46464646  8.54545455  8.6

## working with data types using numpy

In [81]:
## now converting range of values into float datatype
fl_dt = np.arange(1,100,2,dtype=np.float64 )

In [82]:
fl_dt

array([ 1.,  3.,  5.,  7.,  9., 11., 13., 15., 17., 19., 21., 23., 25.,
       27., 29., 31., 33., 35., 37., 39., 41., 43., 45., 47., 49., 51.,
       53., 55., 57., 59., 61., 63., 65., 67., 69., 71., 73., 75., 77.,
       79., 81., 83., 85., 87., 89., 91., 93., 95., 97., 99.])

In [83]:
type(fl_dt)

numpy.ndarray

In [84]:
## now converting float datatype inside list into integer array
lt_dt = np.array([3.6,7.2,3,6,1],dtype=np.int64)

In [85]:
lt_dt

array([3, 7, 3, 6, 1], dtype=int64)

In [87]:
type(lt_dt)

numpy.ndarray

## boolean filtering and indexing

In [88]:
boo = np.arange(2,100,5)

In [89]:
boo

array([ 2,  7, 12, 17, 22, 27, 32, 37, 42, 47, 52, 57, 62, 67, 72, 77, 82,
       87, 92, 97])

In [91]:
boo[boo>=30]

array([32, 37, 42, 47, 52, 57, 62, 67, 72, 77, 82, 87, 92, 97])

In [92]:
boo_arr =np.array ([[
                    [2,3,4],
                    [5,6,7],
                    [8,9,10]
    
]])

In [93]:
boo_arr.ndim

3

In [95]:
boo_arr.shape

(1, 3, 3)

In [97]:
boo_arr>5

array([[[False, False, False],
        [False,  True,  True],
        [ True,  True,  True]]])

In [96]:
boo_arr[boo_arr>5]

array([ 6,  7,  8,  9, 10])

In [103]:
boo_str=np.array(['Tom','Alex','Alice','Maya'])

In [104]:
boo_str

array(['Tom', 'Alex', 'Alice', 'Maya'], dtype='<U5')

In [105]:
boo_str=='Alex'

array([False,  True, False, False])

In [106]:
boo_str[boo_str=='Alex']

array(['Alex'], dtype='<U5')

### working with 2 different arrays in boolean indexing

boo_str

In [108]:
data= np.array([
    [1,2,3,4],
    [6,7,423,8],
    [46,686,343,7],
    [86,3,6,89]
        
    ])

In [109]:
data

array([[  1,   2,   3,   4],
       [  6,   7, 423,   8],
       [ 46, 686, 343,   7],
       [ 86,   3,   6,  89]])

In [110]:
data.shape

(4, 4)

In [111]:
data.ndim

2

In [112]:
boo_str == 'Maya'

array([False, False, False,  True])

In [113]:
data[:,boo_str=='Maya']

array([[ 4],
       [ 8],
       [ 7],
       [89]])

## Arithmetic operations using arrays

In [114]:
arr1 = [1,2,3]
arr2 = [4,5,6]

In [116]:
# its appending the python list
arr1 + arr2

[1, 2, 3, 4, 5, 6]

In [124]:
#appending twice the same list
arr2*2

[4, 5, 6, 4, 5, 6]

In [117]:
arr3 = np.array([1,2,3])
arr4 = np.array([4,5,6])

In [119]:
#while using numpy it adds individual elements inside the array
arr3+arr4

array([5, 7, 9])

In [126]:
#multplying the arr3 array
arr3*2

array([2, 4, 6])

### performing using 2d array

In [121]:
ar1 =  np.array([
            [1,2,4],
            [5,6,7],
            [9,3,7]
])

In [122]:
ar2 = np.array([
            [5,6,3],
            [3,5,9],
            [9,1,2]
])

In [129]:
#multiplying the each elements between two arrays
ar1 * ar2

array([[ 5, 12, 12],
       [15, 30, 63],
       [81,  3, 14]])

In [131]:
#matrix multiplication
ar1 @ ar2

array([[ 47,  20,  29],
       [106,  67,  83],
       [117,  76,  68]])

In [133]:
#same matrix multiplication
np.dot(ar1,ar2)

array([[ 47,  20,  29],
       [106,  67,  83],
       [117,  76,  68]])

## Reshaping the arrays

In [145]:
a1 = np.arange(1,20,2)

In [146]:
a1.shape

(10,)

In [149]:
#reshaping the array into 2x5
rshape = a1.reshape(2,5)

In [150]:
rshape

array([[ 1,  3,  5,  7,  9],
       [11, 13, 15, 17, 19]])

In [152]:
## cascading code
rshape1=np.arange(1,20,2).reshape(5,2)

In [153]:
rshape1

array([[ 1,  3],
       [ 5,  7],
       [ 9, 11],
       [13, 15],
       [17, 19]])

In [173]:
## if we want to change the order of creating arrays, like rows into column

## 1. row-major order

a2 = np.arange(0,20).reshape(4,5, order = 'c')

In [174]:
a2.shape

(4, 5)

In [175]:
a2

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [198]:
# 2.column major order

a3=np.arange(0,20).reshape(4,5, order='f')

In [177]:
a3

array([[ 0,  4,  8, 12, 16],
       [ 1,  5,  9, 13, 17],
       [ 2,  6, 10, 14, 18],
       [ 3,  7, 11, 15, 19]])

In [189]:
## if we don't know how many rows or column should i mention, can use 

a4=np.arange(20)

In [190]:
a4.shape

(20,)

In [191]:
#here i fixed i need 5 rows , so numpy will arrange based on our condition
a4.reshape(5,-1)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [197]:
#here i fixed i need 5 columns , so numpy will arrange based on our condition
a4.reshape(-1,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

## Transposing and flattening

In [201]:
# Transposing the array

arrr = np.arange(20).reshape(4,5)

In [202]:
arrr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [204]:
#transposing the array
arrr.transpose()

array([[ 0,  5, 10, 15],
       [ 1,  6, 11, 16],
       [ 2,  7, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19]])

In [205]:
arrr.T

array([[ 0,  5, 10, 15],
       [ 1,  6, 11, 16],
       [ 2,  7, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19]])

In [213]:
# Flatening ( converting higher dim into 1 dim)
ar_fl = np.arange(20).reshape(5,4)

In [214]:
ar_fl

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [217]:
#converting into 1d array
ar_fll = ar_fl.flatten()

In [218]:
ar_fll.ndim

1

## Concatenating the arrays

In [221]:
arc1 = np.array([ [1,2,3], [4,5,6]])
arc2 = np.array([[7,9,1],[6,1,5]])

In [224]:
print(arc1)
print(arc2)

[[1 2 3]
 [4 5 6]]
[[7 9 1]
 [6 1 5]]


In [227]:
# concatenating the arrays in rows
np.concatenate([arc1, arc2])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 9, 1],
       [6, 1, 5]])

In [229]:
#verticalstack
np.vstack([arc1,arc2])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 9, 1],
       [6, 1, 5]])

In [228]:
# concatenating the arrays in columns /  stacking as columns
np.concatenate([arc1, arc2] , axis=1)

array([[1, 2, 3, 7, 9, 1],
       [4, 5, 6, 6, 1, 5]])

In [230]:
#horizontalstack
np.hstack([arc1,arc2])

array([[1, 2, 3, 7, 9, 1],
       [4, 5, 6, 6, 1, 5]])

## splitting the arrays

In [231]:
sparr = np.arange(20).reshape(4,5)

In [232]:
sparr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [233]:
sparr1 , sparr2,sparr3, sparr4 = np.split(sparr,4)

In [234]:
print(f"sparr1 : {sparr1}")
print(f"sparr2 : {sparr2}")
print(f"sparr3 : {sparr3}")
print(f"sparr4 : {sparr4}")

sparr1 : [[0 1 2 3 4]]
sparr2 : [[5 6 7 8 9]]
sparr3 : [[10 11 12 13 14]]
sparr4 : [[15 16 17 18 19]]


In [245]:
sp1,sp2,sp3 = np.split(sparr,[1,3])

In [247]:
#[:1]
#[1:3]
#[3:]

print(f"sp1 : {sp1}")
print(f"sp2 : {sp2}")
print(f"sp3 : {sp3}")


sp1 : [[0 1 2 3 4]]
sp2 : [[ 5  6  7  8  9]
 [10 11 12 13 14]]
sp3 : [[15 16 17 18 19]]


## Broadcasting

> Two arrays are compatible for broadcasting only if their corresponding axis length matchs or if the either of its length is 1

In [271]:
arrb1 =np.array([[1,2,3]])
arrb2 = np.array([[4,6],
                [3,5]])

In [272]:
print(arrb1.shape)
print(arrb2.shape)

(1, 3)
(2, 2)


In [274]:
#showing error coz the shape doesn't match or even having axis length as 1
arrb1+arrb2

ValueError: operands could not be broadcast together with shapes (1,3) (2,2) 

barr1 = np.arange(54).reshape(6,1,9)
barr2 = np.arange(18).reshape(1,2,9)

In [251]:
print(barr1)

[[[ 0  1  2  3  4  5  6  7  8]]

 [[ 9 10 11 12 13 14 15 16 17]]

 [[18 19 20 21 22 23 24 25 26]]

 [[27 28 29 30 31 32 33 34 35]]

 [[36 37 38 39 40 41 42 43 44]]

 [[45 46 47 48 49 50 51 52 53]]]


In [252]:
print(barr2)

[[[ 0  1  2  3  4  5  6  7  8]
  [ 9 10 11 12 13 14 15 16 17]]]


In [253]:
barr1+barr2

array([[[ 0,  2,  4,  6,  8, 10, 12, 14, 16],
        [ 9, 11, 13, 15, 17, 19, 21, 23, 25]],

       [[ 9, 11, 13, 15, 17, 19, 21, 23, 25],
        [18, 20, 22, 24, 26, 28, 30, 32, 34]],

       [[18, 20, 22, 24, 26, 28, 30, 32, 34],
        [27, 29, 31, 33, 35, 37, 39, 41, 43]],

       [[27, 29, 31, 33, 35, 37, 39, 41, 43],
        [36, 38, 40, 42, 44, 46, 48, 50, 52]],

       [[36, 38, 40, 42, 44, 46, 48, 50, 52],
        [45, 47, 49, 51, 53, 55, 57, 59, 61]],

       [[45, 47, 49, 51, 53, 55, 57, 59, 61],
        [54, 56, 58, 60, 62, 64, 66, 68, 70]]])

## Creating random number

In [277]:
nor_data = np.random.normal(size=(2,5))

In [278]:
nor_data

array([[-2.16128879,  0.43107209, -0.1714667 ,  0.84191365, -0.75553026],
       [ 0.64603971,  2.23010982, -0.54107584, -1.17749789, -0.8161112 ]])

In [291]:
## creating random integer
in_data = np.random.randint(1,50,size=(3,4,5))

In [292]:
in_data

array([[[ 6,  5,  8, 25, 25],
        [45, 35, 41, 16, 14],
        [25, 16,  7, 22, 43],
        [23, 12, 49, 13, 29]],

       [[33, 16, 45, 41, 43],
        [46, 44, 34, 46, 41],
        [26, 10, 38,  1, 19],
        [24,  4, 30, 17, 21]],

       [[19, 49, 15, 16, 18],
        [26, 47, 49, 43, 18],
        [33, 18, 42, 17, 42],
        [27, 13, 31, 18, 18]]])

In [301]:
## using seed can produce same random result
np.random.seed(5)
np.random.randint(2,10, size=(2,5))

array([[5, 8, 9, 7, 8],
       [8, 2, 3, 2, 6]])

In [298]:
#permuting or arranging the random numbers in no of ways
np.random.permutation(10)

array([1, 4, 9, 5, 3, 0, 8, 7, 6, 2])

In [310]:
#shuffling the number
suf = [4,5,7,8,9,21,4]
np.random.shuffle(suf)

In [311]:
suf

[4, 4, 21, 7, 9, 5, 8]

## vectorized operations

In [314]:
x = np.arange(15)

In [315]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [316]:
#squaring
np.square(x)

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196], dtype=int32)

In [318]:
#exponenting
np.exp(x)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04,
       1.62754791e+05, 4.42413392e+05, 1.20260428e+06])

In [319]:
#trignometical function
np.sin(x)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111, -0.99999021, -0.53657292,  0.42016704,  0.99060736])

In [320]:
np.tan(x)

array([ 0.00000000e+00,  1.55740772e+00, -2.18503986e+00, -1.42546543e-01,
        1.15782128e+00, -3.38051501e+00, -2.91006191e-01,  8.71447983e-01,
       -6.79971146e+00, -4.52315659e-01,  6.48360827e-01, -2.25950846e+02,
       -6.35859929e-01,  4.63021133e-01,  7.24460662e+00])

In [321]:
y =np.linspace(1,10,20)

In [322]:
y

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [323]:
#celing
np.ceil(y)

array([ 1.,  2.,  2.,  3.,  3.,  4.,  4.,  5.,  5.,  6.,  6.,  7.,  7.,
        8.,  8.,  9.,  9., 10., 10., 10.])

In [324]:
#flooring
np.floor(y)

array([ 1.,  1.,  1.,  2.,  2.,  3.,  3.,  4.,  4.,  5.,  5.,  6.,  6.,
        7.,  7.,  8.,  8.,  9.,  9., 10.])